# Objective : Learning to solve basic python programs.

In [2]:
# Problem-1
import numpy as np

In [3]:
x = np.random.rand(5,4)
x # here values will be in the range of [0,1) and 1 not included.

array([[0.4884106 , 0.841197  , 0.92972905, 0.81478312],
       [0.00285578, 0.65105409, 0.35460311, 0.77983838],
       [0.6406516 , 0.79429484, 0.75529886, 0.60747899],
       [0.25302004, 0.75900364, 0.02420674, 0.8016658 ],
       [0.55828978, 0.54174369, 0.25533069, 0.84827296]])

In [4]:
x.shape # shape we confuse with "shape()", so be carefull

(5, 4)

In [5]:
print(x.dtype) # dtype gives the data type of the array
# Ususally people get confuse with "dtype()"

float64


In [6]:
s = np.power(8, 10, dtype = np.float64)
s

1073741824.0

In [10]:
x1 = np.random.rand(5,4)
x2 = np.random.rand(5,4)
print(x1+x2)

[[1.24468793 1.13877326 0.73795306 0.15409505]
 [0.73177699 0.78411509 1.37652122 0.3957542 ]
 [0.90644524 0.99578808 0.95638235 1.01284644]
 [0.36048161 1.10601023 1.05686561 0.79701748]
 [1.1248196  0.09236204 0.36532509 0.89647369]]
