# Objective : Learning to solve basic python programs.

In [6]:
# Problem-1
import numpy as np

In [7]:
x = np.random.rand(5,4)
x # here values will be in the range of [0,1) and 1 not included.

array([[0.13118107, 0.3701664 , 0.52010038, 0.46504495],
       [0.62604378, 0.15713982, 0.21198462, 0.01744835],
       [0.43638038, 0.19853765, 0.82892409, 0.74314872],
       [0.2368069 , 0.75695916, 0.03391   , 0.41027571],
       [0.10878187, 0.16202742, 0.32911246, 0.48698386]])

In [8]:
x.shape # shape we confuse with "shape()", so be carefull

(5, 4)

In [9]:
print(x.dtype) # dtype gives the data type of the array
# Ususally people get confuse with "dtype()"

float64


In [10]:
s = np.power(8, 10, dtype = np.float64)
s

1073741824.0

In [11]:
x1 = np.random.rand(5,4)
x2 = np.random.rand(5,4)
print(x1+x2)

[[1.28488698 1.12174426 0.60122713 0.72310632]
 [1.44021069 1.36011726 1.22250356 1.93096767]
 [1.49519877 1.4444935  1.46994956 1.11133906]
 [1.09859196 0.71224191 1.09776039 0.79899483]
 [1.70317288 1.07181178 0.8894128  1.63782745]]


In [12]:
X = x1+x2 
print(X)

[[1.28488698 1.12174426 0.60122713 0.72310632]
 [1.44021069 1.36011726 1.22250356 1.93096767]
 [1.49519877 1.4444935  1.46994956 1.11133906]
 [1.09859196 0.71224191 1.09776039 0.79899483]
 [1.70317288 1.07181178 0.8894128  1.63782745]]


In [13]:
X[2][3]

1.1113390637254144

In [14]:
X[2,3] # here we need not do [2][3] in traditional way, we can directly write [2,3] which it self takes the value 2 as row and 3 as column.Common error people make is X(2,3) which is where the brackets gets confused. but one way of using that brackets is X[(2,3)] which is similar to X[2,3] but not to X(2,3)

1.1113390637254144

In [15]:
X[(2,3)] # X[(2,3)] ~~ X[2,3]

1.1113390637254144

In [16]:
(r, c) = X.shape

In [17]:
print(r)

5


In [18]:
print(c)

4


In [19]:
V = np.zeros((2,3), dtype = 'int')
V

array([[0, 0, 0],
       [0, 0, 0]])

Print("Cx, Cy, Cr")

Cx, Cy, Cr = input().split(' ')

print(Cx, Cy, Cr)



In [20]:
cx, cy, cr = input().split()
print(cx, cy, cr)

ValueError: not enough values to unpack (expected 3, got 0)

In [23]:
a1 = np.random.rand(3,4)
a1


array([[0.17749929, 0.22506567, 0.34221154, 0.86415921],
       [0.36653144, 0.07146516, 0.42740553, 0.94824702],
       [0.81660518, 0.57345792, 0.87124071, 0.9108316 ]])

In [24]:
a2 = np.random.rand(3,7)
a2

array([[0.41193617, 0.42901055, 0.24417962, 0.84921901, 0.24328824,
        0.33719878, 0.51783225],
       [0.19038027, 0.78708828, 0.87049034, 0.73313366, 0.99271455,
        0.05244182, 0.95085023],
       [0.40957963, 0.91577691, 0.03140872, 0.56046124, 0.68978564,
        0.88321091, 0.00288928]])

In [28]:
a = np.hstack((a1, a2))
a

array([[0.17749929, 0.22506567, 0.34221154, 0.86415921, 0.41193617,
        0.42901055, 0.24417962, 0.84921901, 0.24328824, 0.33719878,
        0.51783225],
       [0.36653144, 0.07146516, 0.42740553, 0.94824702, 0.19038027,
        0.78708828, 0.87049034, 0.73313366, 0.99271455, 0.05244182,
        0.95085023],
       [0.81660518, 0.57345792, 0.87124071, 0.9108316 , 0.40957963,
        0.91577691, 0.03140872, 0.56046124, 0.68978564, 0.88321091,
        0.00288928]])