In [1]:
import numpy as np
import time as T

In [7]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
normal_array = np.array([1, 2, 3])
print(normal_array)

[1 2 3]


In [9]:
L = range(1000)
%timeit [i**2 for i in L]

453 µs ± 25.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
a = np.arange(1000)
%timeit a**2

2.43 µs ± 482 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


%timeit is used to check time required to make an operation in a loop and also it will give max and its error change.

In [11]:
numpy_array = np.array([1, 2, 3, 4, 5])
#We can know the dimension using ".ndim"
print(numpy_array.ndim)

1


In [12]:
two_dim_array = np.array([[1,2,3],[4,5,6]])
print(two_dim_array.ndim)
#we can ge shape using ".shape"
print(two_dim_array.shape)

2
(2, 3)


We can find the lenght of single column using "len(array)" and 1D array is called vector,2D array is called matrix, 3D array is called Tensor.

In [13]:
print(len(two_dim_array))

2


In [14]:
b = np.arange(0,100,5) # (start, end, step_size)
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

We can get any number of points in the given range using "linspace".

In [15]:
f = np.linspace(1,2,7)
f

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [16]:
a = np.ones(3)
a

array([1., 1., 1.])

In [17]:
b = np.ones((3,3,3,3))
b

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [13]:
c = np.zeros((4,4,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
d = np.eye(3)# eyes(x,y) --> x = number_of_rows, y = number_of_columns and ones will be diagonal and zeroes else where.
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
e = np.eye(5,6)
e


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [16]:
f = np.diag([1, 2, 3, 4, 5]) # we can create a matrix with diaginal elements as these mentioned and we can also print using n.diag(array)
f

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [17]:
g = np.diag(f)
g

array([1, 2, 3, 4, 5])

In [18]:
h = np.random.rand(4)
h

array([0.2731027 , 0.72187002, 0.30825297, 0.29900583])

In [19]:
I = np.random.randn(5)
I

array([-1.27303152,  0.09169544, -0.38981971,  0.0557907 , -0.09089938])

In [20]:
j = np.arange(10)
j.dtype

dtype('int64')

In [21]:
k = np.arange(10,dtype = 'float64')
k

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
l = np.ones((3,3))
l.dtype

dtype('float64')

In [23]:
m = np.array([1+2j,3+6j])
m.dtype

dtype('complex128')

In [24]:
n = np.diag([1,2,3])
n.dtype

dtype('int64')

In [25]:
o = np.arange(10)
o

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
o[1:9:2] # [start_index : end_index : step]

array([1, 3, 5, 7])

In [27]:
p = np.arange(20)
p[10:] = 100
p

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [28]:
q = np.arange(10)
r = np.arange(15,20)
q[5:] = r[15::-1]
q # here we can't add more elements in q that alloted size initially.

array([ 0,  1,  2,  3,  4, 19, 18, 17, 16, 15])

In [29]:
a1 = np.arange(10)
b = a1[::2]
b

array([0, 2, 4, 6, 8])

In [30]:
np.shares_memory(a1,b)

True

In [31]:
b[1] = 11

In [32]:
a1

array([ 0,  1, 11,  3,  4,  5,  6,  7,  8,  9])

In [33]:
j1 = np.arange(100)
mask = (j1%2 == 0)
extract_from_j1 = j1[mask]
extract_from_j1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])