In [8]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
a - b

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [13]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1+a2

array([5, 7, 9])

In [14]:
a1*a2

array([ 4, 10, 18])

In [15]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([2,2,2,5,5])
x1==x2

array([False,  True, False, False,  True])

In [16]:
x1>x2

array([False, False,  True, False, False])

In [17]:
x1<x2

array([ True, False, False,  True, False])

In [21]:
a = np.array([1, 0, 1, 0],dtype = bool )
b = np.array([0, 1, 0, 1],dtype = bool )
a & b

array([False, False, False, False])

In [22]:
angles = np.arange(90)
np.sin(angles)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11

In [23]:
np.cos(angles)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
       -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293,
       -0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
        0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254,
        0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99

In [24]:
np.log(angles)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406

In [25]:
np.exp(angles)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [26]:
million = np.arange(1000000)

In [27]:
np.sum(million)

499999500000

In [28]:
million

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [2]:
np.all([True,True,False,True])

False

In [3]:
np.all([False,False,True])

False

In [4]:
np.any([True,False,False])

True

In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4,])
((a<b) & (b>c)).all()


True

In [9]:
x = np.arange(11)
x.mean()


5.0

In [10]:
np.mean(x)

5.0

In [11]:
np.median(x)

5.0

In [12]:
x.std()

3.1622776601683795

In [2]:
x = np.tile(np.arange(0,40,10),(3,1))
x

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [9]:
x = np.tile(np.arange(0,40,10),(3,2))
x

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [10]:
x = x.T
x

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [11]:
g = np.tile(np.arange(0,50,10),(4,1))
g

array([[ 0, 10, 20, 30, 40],
       [ 0, 10, 20, 30, 40],
       [ 0, 10, 20, 30, 40],
       [ 0, 10, 20, 30, 40]])

In [13]:
g1 = np.arange(0,5)
g1+g

array([[ 0, 11, 22, 33, 44],
       [ 0, 11, 22, 33, 44],
       [ 0, 11, 22, 33, 44],
       [ 0, 11, 22, 33, 44]])

In [15]:
y1 = np.array([1,2,3,4,5])
y2 = np.array([[1],[2],[3],[4],[5]])
y1+y2

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [16]:
z = np.array([[1,2,3,4,5],[1,2,3,4,5,6,7,8,9,0]])
z.ravel()

array([list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])],
      dtype=object)